spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mydatabase"
    username: root
    password: ăâêồ̉̃́
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: funny123456789123456789123456789
  expiration: 86400
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics